Milestone 4: Bookstore Styling
tresorsawasawa/Bookstore pull request #4
Opened 2022-03-03 23:08 UTC by tresorsawasawa

Tasks filled in this milestone:
- [ ] Add the layout styling from Bookstore design in [Zeplin](https://zeplin.io/) template.

2022-03-03 23:58 UTC, Cathella requested changes
## 🟡 Status: Changes Required 🛑

### Hi @tresorsawasawa 👋🏻, 

Your project looks amazing because you have done a really nice job!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## To Highlight 👏🏻

✅ No linter errors.
✅ You used correct Github Flow.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-03 23:58 UTC, Cathella commented on src/scss/base/_utilities.scss
> +
- [ ] I suggest that you remove this commented out line of code if its no longer needed. This helps in keeping the code-base clean and readable.

2022-03-03 23:58 UTC, Cathella commented on src/scss/base/_variables.scss
> +$v: calc(((18 / 5) * $p - 90) * 1deg);
After the application compiling in my local environment, this variable is frowned upon and cannot allow the project to run further. It only compiles after I comment it out. Below is the screenshot of the error 👇🏻 

![image](https://user-images.githubusercontent.com/4247740/156672917-440511d3-5541-4f72-9015-970c481f3f9b.png)

- [ ] Please kindly fix this error

2022-03-04 00:19 UTC, BrianSammit approved these changes
# STATUS: APPROVED :green_circle: :clap: 

Hello @tresorsawasawa, 
Your project is complete!  There is nothing else to say other than... Great job 👏 
Congratulations! 🎉 

TO HIGHLIGHT:

- Your project is professional 
- Your repo is professional 
- Well structured files 


Now you can merge this branch and move on :1st_place_medal: 
HAPPY CODING AND GOOD LUCK WITH THE COMMING ONES :crossed_fingers: :four_leaf_clover: 

![well-1](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-04 00:25 UTC, merged